export enum MedicalSpecialty {
  ALERGIA_E_IMUNOLOGIA = 'Alergia e Imunologia',
  ANESTESIOLOGIA = 'Anestesiologia',
  ANGIOLOGIA = 'Angiologia',
  CANCEROLOGIA = 'Cancerologia',
  CARDIOLOGIA = 'Cardiologia',
  CIRURGIA_CARDIOVASCULAR = 'Cirurgia Cardiovascular',
  CIRURGIA_CABECA_PESCOCO = 'Cirurgia de Cabeça e Pescoço',
  CIRURGIA_DIGESTIVA = 'Cirurgia do Aparelho Digestivo',
  CIRURGIA_GERAL = 'Cirurgia Geral',
  CIRURGIA_PEDIATRICA = 'Cirurgia Pediátrica',
  CIRURGIA_PLASTICA = 'Cirurgia Plástica',
  CIRURGIA_TORACICA = 'Cirurgia Torácica',
  CIRURGIA_VASCULAR = 'Cirurgia Vascular',
  CLINICA_MEDICA = 'Clínica Médica',
  DERMATOLOGIA = 'Dermatologia',
  ENDOCRINOLOGIA = 'Endocrinologia e Metabologia',
  ENDOSCOPIA = 'Endoscopia',
  GASTROENTEROLOGIA = 'Gastroenterologia',
  GERIATRIA = 'Geriatria',
  GINECOLOGIA_OBSTETRICIA = 'Ginecologia e Obstetrícia',
  HEMATOLOGIA = 'Hematologia e Hemoterapia',
  HEPATOLOGIA = 'Hepatologia',
  HOMEOPATIA = 'Homeopatia',
  INFECTOLOGIA = 'Infectologia',
  MASTOLOGIA = 'Mastologia',
  MEDICINA_DE_EMERGENCIA = 'Medicina de Emergência',
  MEDICINA_DO_TRABALHO = 'Medicina do Trabalho',
  MEDICINA_DE_FAMILIA = 'Medicina de Família e Comunidade',
  MEDICINA_ESPORTIVA = 'Medicina Esportiva',
  NEFROLOGIA = 'Nefrologia',
  NEUROCIRURGIA = 'Neurocirurgia',
  NEUROLOGIA = 'Neurologia',
  NUTROLOGIA = 'Nutrologia',
  OFTALMOLOGIA = 'Oftalmologia',
  ONCOLOGIA_CLINICA = 'Oncologia Clínica',
  ORTOPEDIA = 'Ortopedia e Traumatologia',
  OTORRINOLARINGOLOGIA = 'Otorrinolaringologia',
  PATOLOGIA = 'Patologia',
  PEDIATRIA = 'Pediatria',
  PNEUMOLOGIA = 'Pneumologia',
  PSIQUIATRIA = 'Psiquiatria',
  RADIOLOGIA = 'Radiologia e Diagnóstico por Imagem',
  REUMATOLOGIA = 'Reumatologia',
  UROLOGIA = 'Urologia',
}

// converte em objeto para usar em selects
export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  }),
);
